### ISSUE TITLE
Analysis Roadmap

### ISSUE THREAD

**Issue by 18ganesha** [BrownDwarf/disperse#3]
- [ ] make semiautomated table completely automated for csv file using [pandas function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_latex.html) and transfer to Latex
- [ ] throw out lines with very high ew_unc values for plots, keep in csv files
- [ ] see if multiple objects have noisy spectra or if it is just for a particular object
- [ ] populate a table of stellar characteristics with the [NASA Exoplanet Archive](https://exoplanetarchive.ipac.caltech.edu/)
- [ ] spot check the wavelength bounds for different objects to ensure MCMC will run properly
- [ ] save plot in separate files if finding a lot of problems with bounds (optional)
- [ ] correct for Earth's velocity using astropy: barycentric velocity correction (HPF might have in header)
- [ ] quality assurance test based on gaussian width, add to csv file
