### ISSUE TITLE
Results Roadmap

### ISSUE THREAD

**Issue by 18ganesha** [BrownDwarf/disperse#4]
- [ ] include all information from unc vs time plot of all planets into a few plots/figures

OR

- [ ] include specific unc vs time plots with certain qualities that are unique from others
- [x] compute mean/median of out-of-transit/in-transit 
- [ ] calculate horizontal line: median of out-of-transit vs weighted mean based on unc
- [x] plot horizontal line between error bars to see if they out-of-transit points touch the line
- [x] overplot light curve to ew as a visualization for paper (*extra credit*)
