### ISSUE TITLE
Paper Roadmap

### ISSUE THREAD

**Issue by 18ganesha** [BrownDwarf/disperse#5]
- [ ] create a bilbiography of literature with articles that relate heavily to the HPF spectra research we are doing
- [ ] read papers about the different types of stellar activity (flares, rotational variability, etc.) and see how they change spectra
- [ ] make an ordered list of effects that can mimic a helium exosphere
