### ISSUE TITLE
Refactor Roadmap

### ISSUE THREAD

**Issue by 18ganesha** [BrownDwarf/disperse#6]
- [ ] make a folder called 'deprecated' with older jupyter notebook that clutter up the repo
- [ ] make one jupyter notebook as a tutortial with clear step by step instructions
- [ ] install `gollum` to implement sliders
- [ ] migrate functions such as `measure_ew()` to script instead of having to search through old `disperse` notebooks
