### ISSUE TITLE
Implementation Roadmap

### ISSUE THREAD

**Issue by 18ganesha** [BrownDwarf/disperse#7]
- [ ] talk with Jessica if there will be interest in 67b
- [ ] confirm which planets from our data will coincide with TESS data this Fall (will HAT-P-67 be revisted)
- [ ] take into account the telluric lines and subtract them from the spectra
- [ ] take into account any other contamination due to Earth or the instrument
